spring.application.name=dynamic-pricing-engine

server.port=8080

# =========================
# MySQL
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/dynamic_pricing_engine
spring.datasource.username=root
spring.datasource.password=your_password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Cache
# =========================
spring.cache.type=simple
